@test_token=eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiUGVhY2ggQWxnYWUiLCJpc1ByZW1pdW0iOnRydWUsImVtYWlsIjoicGVhY2guYWxnYWUuNTAzQGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF1dGhfdGltZSI6MTYxMTUxNjUwMCwidXNlcl9pZCI6IlRlZVBlVEFWVm9kMElzeG5EYzl1UkcyZ2lWNkIiLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInBlYWNoLmFsZ2FlLjUwM0BleGFtcGxlLmNvbSJdLCJnb29nbGUuY29tIjpbIjUwMTI3ODYxOTA0NjE0NjgzMzg3NTAwMTgzOTIxNTU3NjY0NDc4OTkiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn0sImlhdCI6MTYxMTUxNjUwMCwiZXhwIjoxNjExNTIwMTAwLCJhdWQiOiJwbGF5Z3JvdW5kLWQwZmJlIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL3BsYXlncm91bmQtZDBmYmUiLCJzdWIiOiJUZWVQZVRBVlZvZDBJc3huRGM5dVJHMmdpVjZCIn0.

###
GET http://localhost:5001/playground-d0fbe/us-central1/api/premium/checkout
Authorization: Bearer {{test_token}}
###
POST http://localhost:5001/playground-d0fbe/us-central1/api/premium/cancel
Authorization: Bearer {{test_token}}